name: presubmits
on:
  pull_request:
    branches:
      - main
jobs:
  # Runs smart contract test code located in
  # backend/test using Truffle.
  smart-contract-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm install -g babel-runtime
      - run: npm install -g truffle
      - run: npm install -g ganache-cli
      - run: ganache-cli --accounts 25 --defaultBalanceEther 10000000 -l 80000000000000 > /dev/null &
      - run: truffle test
